// import '../libs.dart';

// List<Round> rounds = [
//   Round(
//     active: false,
//     activeAmount: 0.00,
//     categoryID: 1,
//     createdAt: Date(year: 2012, month: 1, day: 5),
//     endDate: "5/6/2012",
//     fee: 4000,
//     lang: "Eng",
//     roundNumber: 1,
//     startDate: "5/5/2012",
//     students: 50,
//     trainingHours: 20,
//     id: 1,
//   ),
//   Round(
//     active: true,
//     activeAmount: 0.00,
//     categoryID: 1,
//     createdAt: Date(year: 2012, month: 1, day: 5),
//     endDate: "5/6/2012",
//     fee: 4000,
//     lang: "Eng",
//     roundNumber: 55,
//     startDate: "5/5/2012",
//     students: 50,
//     trainingHours: 20,
//     id: 3,
//   ),
//   Round(
//     active: true,
//     activeAmount: 0.00,
//     categoryID: 1,
//     createdAt: Date(year: 2012, month: 1, day: 5),
//     endDate: "5/6/2012",
//     fee: 4000,
//     lang: "Eng",
//     roundNumber: 123,
//     startDate: "5/5/2012",
//     students: 50,
//     trainingHours: 20,
//     id: 2,
//   ),
//   Round(
//     active: false,
//     activeAmount: 0.00,
//     categoryID: 1,
//     createdAt: Date(year: 2012, month: 1, day: 5),
//     endDate: "5/6/2012",
//     fee: 4000,
//     lang: "Eng",
//     roundNumber: 1,
//     startDate: "5/5/2012",
//     students: 50,
//     trainingHours: 20,
//     id: 4,
//   ),
// ];
